### PR TITLE
Structure the README with project status

### PR DESCRIPTION
**Pull request by LeoColomb**
Shall we archive GAE and lighttpd?

### CODE REVIEW

**Comment by LeoColomb** [comment]
@roblarsen 😊

**Comment by gstrauss** [comment]
> Shall we archive GAE and lighttpd?

Why archive lighttpd?  lighttpd is actively maintained (hi! I am a lighttpd developer) and is the default webserver on many small systems, e.g. RaspberryPi, and embedded systems.

That said, https://github.com/h5bp/server-configs-lighttpd/blob/master/lighttpd.conf could use some minor updating.

**Comment by roblarsen** [comment]
@LeoColomb to me, if the configs aren't useful, then we should archive them. If they're still useful and just stale, that's okay. I don't know enough about either tech to make that call.

**Comment by LeoColomb** [comment]
> Why archive lighttpd?

@gstrauss I'm talking about H5BP config _for_ lighttpd of course, not lighttpd by itself on which we have literally zero right to archive anything. 🤔 
But glad to hear you are the maintainer. Are you interested into maintaining that H5BP config boilerplate as well?
Or even better, is it possible to make lighttpd default values as close as possible from current web standard recommendations? I have no idea, how much (or how little) it deviates from these recommendations today, but another way to maintain H5BP configs is to make them widely irrelevant with solid default config. 💪 

@roblarsen That's fine for me, then the PR is ready 😊

**Comment by gstrauss** [comment]
I submitted PR yesterday: https://github.com/h5bp/server-configs-lighttpd/pull/4

There is no one-size-fits-all web configuration, though there are conventions and a generic recommended starting config.

The PR I submitted generally kept the same caching settings as the prior config, even though caching settings can be very site-specific.

**Comment by gstrauss** [comment]
> Or even better, is it possible to make lighttpd default values as close as possible from current web standard recommendations?

There are literally thousands of pages of HTTP-related RFCs.
Depending on the site frameworks, there are thousands of more pages discussing best practices.  Best practices for security.  Best practices for mobile.  Best practices for widest browser compatibility.  ...   some of these best practices make tradeoffs, and some conflict with other recommendations, depending on what you prioritize for your site.

> I have no idea how much (or how little) it deviates from these recommendations today, but another (and better) way to maintain H5BP configs is to make them widely irrelevant with solid default config.

lighttpd aims to be RFC-compliant by default and the lighttpd default config template shipped with lighttpd source code does so.  However, there are many, many, many optional features to HTTP RFCs and lighttpd configuation.  There is no one-size-fits-all.

FYI: the most basic lighttpd config is a single line which specifies from where to serve files: `server.document-root = "..."`

**Comment by LeoColomb** [comment]
@gstrauss Let's continue the discussion on https://github.com/h5bp/server-configs-lighttpd/issues/5 😊
@roblarsen Let me know about the pull request 😊

**Review by roblarsen — APPROVED** [review]
👍

**Comment by LeoColomb** [comment]
(@roblarsen I can't merge on this repo, or do anything else actually 😅)

**Comment by roblarsen** [comment]
@LeoColomb I just added you to the correct team to manage this repo. You should also... manage that team! I don't know half the people myself, so you might know better than I do if those people should still have access.

**Pull request merged**
